"""Regenerate native pybind stubs and the top-level tactile re-export stub."""

import ast
import re

import pybind11_stubgen


def main():
    pybind11_stubgen.main(["wujihandpy._core", "-o", "src"])
    post_process_async_function()
    post_process_tactile_callbacks()
    write_top_level_tactile_stub()


def post_process_async_function():
    with open("src/wujihandpy/_core/__init__.pyi", "r", encoding="utf-8") as file:
        content = file.read()

    sections = content.split("class")
    for i in range(len(sections)):
        return_type_dict: dict[str, str] = {}
        matches = re.finditer(r"def (read|write)_(\S+?)\(.+?\) -> ([^:]+):", sections[i])
        for match in matches:
            groups = match.groups()
            if not groups[1].endswith("async") and not groups[1].endswith("unchecked"):
                return_type_dict[f"{groups[0]}_{groups[1]}"] = groups[2].strip()

        for key, value in return_type_dict.items():
            sections[i] = re.sub(
                rf"def {key}_async\((.+?)\) -> typing\.Any:",
                lambda match: f"def {key}_async({match.group(1)}) -> typing.Awaitable[{value}]:",
                sections[i],
            )

    content = "class".join(sections)
    content = re.sub(r"\bnumpy\.bool\b", "numpy.bool_", content)

    # pybind11_stubgen emits `typing.SupportsFloat | typing.SupportsIndex` for
    # every `double` arg because pybind11's float coercion accepts ints. The
    # SupportsIndex branch is semantically misleading for timeout/duration
    # arguments — narrow to plain SupportsFloat.
    content = re.sub(
        r"timeout: typing\.SupportsFloat \| typing\.SupportsIndex",
        "timeout: typing.SupportsFloat",
        content,
    )

    with open("src/wujihandpy/_core/__init__.pyi", "w", encoding="utf-8") as file:
        file.write(content)


def post_process_tactile_callbacks():
    """Tighten `Callable` -> typed callbacks in tactile.pyi.

    pybind11_stubgen emits `collections.abc.Callable` (no parameter types) for
    pybind11 std::function bindings; for our two well-known callbacks we know
    the exact signature and want it surfaced in IDEs/type-checkers.
    """
    path = "src/wujihandpy/_core/tactile.pyi"
    with open(path, "r", encoding="utf-8") as file:
        content = file.read()
    content = content.replace(
        "def set_disconnect_callback(self, callback: collections.abc.Callable) -> None:",
        "def set_disconnect_callback(self, callback: collections.abc.Callable[[], None]) -> None:",
    )
    content = content.replace(
        "def start_streaming(self, callback: collections.abc.Callable) -> None:",
        "def start_streaming(self, callback: collections.abc.Callable[[Frame], None]) -> None:",
    )
    with open(path, "w", encoding="utf-8") as file:
        file.write(content)


def _all_assignment(node):
    """Return (target, value) for `__all__ = ...` / `__all__: T = ...`, else (None, None)."""
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return node.target, node.value
    if (isinstance(node, ast.Assign) and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)):
        return node.targets[0], node.value
    return None, None


def write_top_level_tactile_stub():
    """Generate src/wujihandpy/tactile.pyi from _core/tactile.pyi's __all__."""
    with open("src/wujihandpy/_core/tactile.pyi", "r", encoding="utf-8") as f:
        tree = ast.parse(f.read())

    names = None
    for node in ast.walk(tree):
        target, value = _all_assignment(node)
        if target is not None and target.id == "__all__" and isinstance(value, ast.List):
            names = sorted(ast.literal_eval(value))
            break
    if not names:
        raise RuntimeError(
            "src/wujihandpy/_core/tactile.pyi has no parseable __all__; "
            "regenerate _core/tactile.pyi first or fix the stubgen output."
        )

    indent = " " * 4
    body = (
        '"""Type stub for wujihandpy.tactile (generated by update_stubs.py)."""\n\n'
        'from __future__ import annotations\n\n'
        'from ._core.tactile import (\n'
        + "".join(f"{indent}{n} as {n},\n" for n in names)
        + ')\n\n'
        '__all__: list[str] = [\n'
        + "".join(f'{indent}"{n}",\n' for n in names)
        + ']\n'
    )

    with open("src/wujihandpy/tactile.pyi", "w", encoding="utf-8") as f:
        f.write(body)


if __name__ == "__main__":
    main()
