"""Regenerate Python type stubs.

Two outputs:

  src/wujihandpy/_core/*.pyi
    pybind11_stubgen output for the native module. Includes a
    `tactile` submodule stub (src/wujihandpy/_core/tactile.pyi) listing
    every name exposed by m.def_submodule("tactile", ...).

  src/wujihandpy/tactile.pyi
    Hand-friendly re-export so type checkers see
    `from wujihandpy.tactile import Board` resolve to the correct
    pybind class. Generated mechanically from _core/tactile.pyi's
    __all__ — no manual editing needed.
"""

import ast
import re
import typing

import pybind11_stubgen


def main():
    pybind11_stubgen.main(["wujihandpy._core", "-o", "src"])
    post_process_async_function()
    write_top_level_tactile_stub()


def post_process_async_function():
    with open("src/wujihandpy/_core/__init__.pyi", "r") as file:
        content = file.read()

    sections = content.split("class")
    for i in range(len(sections)):
        return_type_dict: typing.Dict[str, str] = {}
        matches = re.finditer(r"def (read|write)_(\S+?)\(.+?\) -> ([^:]+):", sections[i])
        for match in matches:
            groups = match.groups()
            if not groups[1].endswith("async") and not groups[1].endswith("unchecked"):
                return_type_dict[f"{groups[0]}_{groups[1]}"] = groups[2].strip()

        for key, value in return_type_dict.items():
            sections[i] = re.sub(
                rf"def {key}_async\((.+?)\) -> typing\.Any:",
                lambda match: f"def {key}_async({match.group(1)}) -> typing.Awaitable[{value}]:",
                sections[i],
            )

    content = "class".join(sections)

    content = re.sub(r"\bnumpy\.bool\b", "numpy.bool_", content)

    with open("src/wujihandpy/_core/__init__.pyi", "w") as file:
        file.write(content)


def write_top_level_tactile_stub():
    """Mirror src/wujihandpy/tactile.py's runtime re-exports as a stub.

    Reads __all__ from src/wujihandpy/_core/tactile.pyi (authoritative
    list of pybind-registered names) and emits a stub that re-exports
    each one with the `from X import Y as Y` form pyright/mypy treat
    as a typed re-export. Keeps src/wujihandpy/tactile.pyi in lockstep
    with the native submodule so it never drifts when the SDK adds or
    removes a tactile type.
    """
    with open("src/wujihandpy/_core/tactile.pyi", "r") as f:
        tree = ast.parse(f.read())

    names = None
    for node in ast.walk(tree):
        # stubgen emits `__all__: list[str] = [...]` which parses as
        # AnnAssign, not Assign.
        target = None
        value = None
        if (isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)):
            target, value = node.target, node.value
        elif (isinstance(node, ast.Assign)
                and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name)):
            target, value = node.targets[0], node.value
        if target is None or target.id != "__all__":
            continue
        if isinstance(value, ast.List):
            names = [elt.value for elt in value.elts
                     if isinstance(elt, ast.Constant)]
            break
    if not names:
        raise RuntimeError(
            "src/wujihandpy/_core/tactile.pyi has no parseable __all__; "
            "regenerate _core/tactile.pyi first or fix the stubgen output."
        )

    names = sorted(names)
    indent = " " * 4
    body = (
        '"""Type stub for wujihandpy.tactile.\n'
        '\n'
        'Mirrors the runtime re-exports in tactile.py so type checkers\n'
        '(mypy / pyright) resolve `from wujihandpy.tactile import Board`\n'
        'to the classes pybind11_stubgen wrote into _core/tactile.pyi.\n'
        '\n'
        'Generated by update_stubs.py — do not edit by hand.\n'
        '"""\n\n'
        'from __future__ import annotations\n\n'
        'from ._core.tactile import (\n'
        + "".join(f"{indent}{n} as {n},\n" for n in names)
        + ')\n\n'
        '__all__: list[str] = [\n'
        + "".join(f'{indent}"{n}",\n' for n in names)
        + ']\n'
    )

    with open("src/wujihandpy/tactile.pyi", "w") as f:
        f.write(body)


if __name__ == "__main__":
    main()
