from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
from . import filter
from . import logging
__all__: list[str] = ['Finger', 'Hand', 'IController', 'Joint', 'TactileBoard', 'TactileDeviceInfo', 'TactileDeviceTime', 'TactileDiagnostics', 'TactileError', 'TactileFrame', 'TactileFwBuild', 'TactileHandedness', 'TactileStatus', 'TactileSyncResult', 'filter', 'logging']
class Finger:
    def get_joint_actual_position(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_bus_voltage(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def get_joint_current_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_effort_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_error_code(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_firmware_date(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_firmware_version(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_lower_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_temperature(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def get_joint_upper_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def joint(self, index: typing.SupportsInt | typing.SupportsIndex) -> Joint:
        ...
    def read_joint_actual_position(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_actual_position_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_actual_position_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_bus_voltage(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def read_joint_bus_voltage_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float32]]:
        ...
    def read_joint_bus_voltage_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_current_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_current_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_current_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_effort_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_effort_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_effort_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_error_code(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_error_code_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_error_code_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_date(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_firmware_date_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_firmware_date_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_version(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_firmware_version_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_firmware_version_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_lower_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_lower_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_lower_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_temperature(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def read_joint_temperature_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float32]]:
        ...
    def read_joint_temperature_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_upper_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_upper_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_upper_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_control_mode_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_control_mode_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_current_limit_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_current_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_effort_limit_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_effort_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled_async(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_enabled_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_enabled_unchecked(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_reset_error_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_reset_error_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_sin_level_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_sin_level_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_target_position_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_target_position_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
class Hand:
    def __init__(self, serial_number: str | None = None, usb_pid: typing.SupportsInt | typing.SupportsIndex = -1, usb_vid: typing.SupportsInt | typing.SupportsIndex = 1155, mask: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_] | None = None) -> None:
        ...
    def disable_thread_safe_check(self) -> None:
        """
        Disable thread safety check to allow multi-threaded usage. When disabled, user must ensure thread-safe access using external mutex.
        """
    def finger(self, index: typing.SupportsInt | typing.SupportsIndex) -> Finger:
        ...
    def get_firmware_date(self) -> numpy.uint32:
        ...
    def get_firmware_version(self) -> numpy.uint32:
        ...
    def get_handedness(self) -> numpy.uint8:
        ...
    def get_input_voltage(self) -> numpy.float32:
        ...
    def get_joint_actual_position(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_bus_voltage(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def get_joint_current_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_effort_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_error_code(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_firmware_date(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_firmware_version(self) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def get_joint_lower_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_temperature(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def get_joint_upper_limit(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_product_sn(self) -> str:
        """
        Get device product serial number
        """
    def get_system_time(self) -> numpy.uint32:
        ...
    def get_temperature(self) -> numpy.float32:
        ...
    def raw_sdo_read(self, finger_id: typing.SupportsInt | typing.SupportsIndex, joint_id: typing.SupportsInt | typing.SupportsIndex, index: typing.SupportsInt | typing.SupportsIndex, sub_index: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> bytes:
        ...
    def raw_sdo_write(self, finger_id: typing.SupportsInt | typing.SupportsIndex, joint_id: typing.SupportsInt | typing.SupportsIndex, index: typing.SupportsInt | typing.SupportsIndex, sub_index: typing.SupportsInt | typing.SupportsIndex, data: bytes, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_firmware_date(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_firmware_date_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_firmware_date_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_firmware_version(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_firmware_version_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_firmware_version_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_handedness(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint8:
        ...
    def read_handedness_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint8]:
        ...
    def read_handedness_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_input_voltage(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float32:
        ...
    def read_input_voltage_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float32]:
        ...
    def read_input_voltage_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_actual_position(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_actual_position_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_actual_position_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_bus_voltage(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def read_joint_bus_voltage_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float32]]:
        ...
    def read_joint_bus_voltage_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_current_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_current_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_current_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_effort_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_effort_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_effort_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_error_code(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_error_code_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_error_code_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_date(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_firmware_date_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_firmware_date_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_version(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.uint32]:
        ...
    def read_joint_firmware_version_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.uint32]]:
        ...
    def read_joint_firmware_version_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_lower_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_lower_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_lower_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_temperature(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def read_joint_temperature_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float32]]:
        ...
    def read_joint_temperature_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_upper_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def read_joint_upper_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.typing.NDArray[numpy.float64]]:
        ...
    def read_joint_upper_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_system_time(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_system_time_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_system_time_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_temperature(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float32:
        ...
    def read_temperature_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float32]:
        ...
    def read_temperature_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def realtime_controller(self, enable_upstream: bool, filter: filter.IFilter) -> IController:
        ...
    def start_latency_test(self) -> None:
        ...
    def stop_latency_test(self) -> None:
        ...
    @typing.overload
    def write_joint_control_mode(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_control_mode_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_control_mode_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_control_mode_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_current_limit_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_current_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_current_limit_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_effort_limit_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_effort_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_effort_limit_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled_async(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_enabled_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_enabled_unchecked(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_enabled_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.bool_], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_reset_error_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_reset_error_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_reset_error_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_sin_level_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_sin_level_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_sin_level_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.uint16], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_target_position_async(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    @typing.overload
    def write_joint_target_position_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    @typing.overload
    def write_joint_target_position_unchecked(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64], timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
class IController:
    def __enter__(self) -> IController:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    def close(self) -> None:
        ...
    def get_joint_actual_effort(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def get_joint_actual_position(self) -> numpy.typing.NDArray[numpy.float64]:
        ...
    def set_joint_target_position(self, value_array: typing.Annotated[numpy.typing.ArrayLike, numpy.float64]) -> None:
        ...
class Joint:
    def get_joint_actual_position(self) -> numpy.float64:
        ...
    def get_joint_bus_voltage(self) -> numpy.float32:
        ...
    def get_joint_current_limit(self) -> numpy.float64:
        ...
    def get_joint_effort_limit(self) -> numpy.float64:
        ...
    def get_joint_error_code(self) -> numpy.uint32:
        ...
    def get_joint_firmware_date(self) -> numpy.uint32:
        ...
    def get_joint_firmware_version(self) -> numpy.uint32:
        ...
    def get_joint_lower_limit(self) -> numpy.float64:
        ...
    def get_joint_temperature(self) -> numpy.float32:
        ...
    def get_joint_upper_limit(self) -> numpy.float64:
        ...
    def read_joint_actual_position(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float64:
        ...
    def read_joint_actual_position_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float64]:
        ...
    def read_joint_actual_position_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_bus_voltage(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float32:
        ...
    def read_joint_bus_voltage_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float32]:
        ...
    def read_joint_bus_voltage_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_current_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float64:
        ...
    def read_joint_current_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float64]:
        ...
    def read_joint_current_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_effort_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float64:
        ...
    def read_joint_effort_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float64]:
        ...
    def read_joint_effort_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_error_code(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_joint_error_code_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_joint_error_code_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_date(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_joint_firmware_date_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_joint_firmware_date_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_firmware_version(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.uint32:
        ...
    def read_joint_firmware_version_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.uint32]:
        ...
    def read_joint_firmware_version_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_lower_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float64:
        ...
    def read_joint_lower_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float64]:
        ...
    def read_joint_lower_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_temperature(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float32:
        ...
    def read_joint_temperature_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float32]:
        ...
    def read_joint_temperature_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def read_joint_upper_limit(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> numpy.float64:
        ...
    def read_joint_upper_limit_async(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[numpy.float64]:
        ...
    def read_joint_upper_limit_unchecked(self, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_control_mode(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_control_mode_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_control_mode_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_current_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_current_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_current_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_effort_limit(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_effort_limit_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_effort_limit_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_enabled(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_enabled_async(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_enabled_unchecked(self, value: bool, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_reset_error(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_reset_error_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_reset_error_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_sin_level(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_sin_level_async(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_sin_level_unchecked(self, value: typing.SupportsInt | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_target_position(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def write_joint_target_position_async(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> typing.Awaitable[None]:
        ...
    def write_joint_target_position_unchecked(self, value: typing.SupportsFloat | typing.SupportsIndex, timeout: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
class TactileBoard:
    BOOTLOADER_MAGIC: typing.ClassVar[int] = 2953293831
    def __enter__(self) -> TactileBoard:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    def __init__(self, serial_number: str | None = None) -> None:
        ...
    def connect(self) -> bool:
        ...
    def disconnect(self) -> None:
        ...
    def enter_bootloader(self, magic: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def get_device_info(self) -> TactileDeviceInfo:
        ...
    def get_device_time(self) -> TactileDeviceTime:
        ...
    def get_diagnostics(self) -> TactileDiagnostics:
        ...
    def get_fw_build(self) -> TactileFwBuild:
        ...
    def get_handedness(self) -> TactileHandedness:
        ...
    def get_sample_rate_hz(self) -> int:
        ...
    def get_streaming_enabled(self) -> bool:
        ...
    def is_connected(self) -> bool:
        ...
    def read_frame(self, timeout_ms: typing.SupportsInt | typing.SupportsIndex = 100) -> TactileFrame:
        ...
    def reset_counters(self) -> None:
        ...
    def reset_device(self) -> None:
        ...
    def set_disconnect_callback(self, callback: collections.abc.Callable) -> None:
        ...
    def set_sample_rate_hz(self, sample_rate_hz: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_streaming(self, enable: bool) -> None:
        ...
    def start_streaming(self, callback: collections.abc.Callable) -> None:
        ...
    def stop_streaming(self) -> None:
        ...
    def sync_host_epoch(self, host_unix_ns: typing.SupportsInt | typing.SupportsIndex) -> TactileSyncResult:
        ...
class TactileDeviceInfo:
    @property
    def fw_version(self) -> typing.Annotated[list[int], "FixedSize(4)"]:
        ...
    @property
    def hw_revision(self) -> typing.Annotated[list[int], "FixedSize(4)"]:
        ...
    @property
    def serial(self) -> str:
        ...
class TactileDeviceTime:
    @property
    def device_monotonic_ns(self) -> int:
        ...
class TactileDiagnostics:
    @property
    def crc_err_count(self) -> int:
        ...
    @property
    def dropout_count(self) -> int:
        ...
    @property
    def frame_count(self) -> int:
        ...
    @property
    def uptime_ms(self) -> int:
        ...
    @property
    def usb_reset_count(self) -> int:
        ...
class TactileError(Exception):
    pass
class TactileFrame:
    @property
    def crc_valid(self) -> bool:
        ...
    @property
    def hand(self) -> TactileHandedness:
        ...
    @property
    def pressure(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    @property
    def sequence(self) -> int:
        ...
    @property
    def timestamp_ms(self) -> int:
        ...
class TactileFwBuild:
    @property
    def git_short_sha(self) -> str:
        ...
class TactileHandedness:
    """
    Members:
    
      LEFT
    
      RIGHT
    """
    LEFT: typing.ClassVar[TactileHandedness]  # value = <TactileHandedness.LEFT: 0>
    RIGHT: typing.ClassVar[TactileHandedness]  # value = <TactileHandedness.RIGHT: 1>
    __members__: typing.ClassVar[dict[str, TactileHandedness]]  # value = {'LEFT': <TactileHandedness.LEFT: 0>, 'RIGHT': <TactileHandedness.RIGHT: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TactileStatus:
    """
    Members:
    
      OK
    
      BAD_LENGTH
    
      BAD_CRC
    
      UNKNOWN_CMD
    
      BAD_PAYLOAD
    """
    BAD_CRC: typing.ClassVar[TactileStatus]  # value = <TactileStatus.BAD_CRC: 17>
    BAD_LENGTH: typing.ClassVar[TactileStatus]  # value = <TactileStatus.BAD_LENGTH: 16>
    BAD_PAYLOAD: typing.ClassVar[TactileStatus]  # value = <TactileStatus.BAD_PAYLOAD: 19>
    OK: typing.ClassVar[TactileStatus]  # value = <TactileStatus.OK: 0>
    UNKNOWN_CMD: typing.ClassVar[TactileStatus]  # value = <TactileStatus.UNKNOWN_CMD: 18>
    __members__: typing.ClassVar[dict[str, TactileStatus]]  # value = {'OK': <TactileStatus.OK: 0>, 'BAD_LENGTH': <TactileStatus.BAD_LENGTH: 16>, 'BAD_CRC': <TactileStatus.BAD_CRC: 17>, 'UNKNOWN_CMD': <TactileStatus.UNKNOWN_CMD: 18>, 'BAD_PAYLOAD': <TactileStatus.BAD_PAYLOAD: 19>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TactileSyncResult:
    @property
    def device_ns_at_sync(self) -> int:
        ...
    @property
    def host_ns_echo(self) -> int:
        ...
