"""
Tactile board API (wujihandcpp::tactile namespace).
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list = ['BOOTLOADER_MAGIC', 'DeviceInfo', 'DeviceTime', 'Diagnostics', 'Error', 'Frame', 'FwBuild', 'Glove', 'Handedness', 'Status', 'SyncResult']
class DeviceInfo:
    @property
    def fw_version(self) -> typing.Annotated[list[int], "FixedSize(4)"]:
        ...
    @property
    def hw_revision(self) -> typing.Annotated[list[int], "FixedSize(4)"]:
        ...
    @property
    def serial(self) -> str:
        ...
class DeviceTime:
    @property
    def device_monotonic_ns(self) -> int:
        ...
class Diagnostics:
    @property
    def crc_err_count(self) -> int:
        ...
    @property
    def dropout_count(self) -> int:
        ...
    @property
    def frame_count(self) -> int:
        ...
    @property
    def uptime_ms(self) -> int:
        ...
    @property
    def usb_reset_count(self) -> int:
        ...
class Error(Exception):
    pass
class Frame:
    @property
    def hand(self) -> Handedness:
        ...
    @property
    def pressure(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    @property
    def sequence(self) -> int:
        ...
    @property
    def timestamp_ms(self) -> int:
        ...
class FwBuild:
    @property
    def git_short_sha(self) -> str:
        ...
class Glove:
    def __enter__(self) -> Glove:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    def __init__(self, serial_number: str | None = None) -> None:
        ...
    def connect(self) -> bool:
        ...
    def disconnect(self) -> None:
        ...
    def enter_bootloader(self, magic: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def get_device_info(self) -> DeviceInfo:
        ...
    def get_device_time(self) -> DeviceTime:
        ...
    def get_diagnostics(self) -> Diagnostics:
        ...
    def get_fw_build(self) -> FwBuild:
        ...
    def get_handedness(self) -> Handedness:
        ...
    def get_sample_rate_hz(self) -> int:
        ...
    def get_streaming_enabled(self) -> bool:
        ...
    def is_connected(self) -> bool:
        ...
    def read_frame(self, timeout_ms: typing.SupportsInt | typing.SupportsIndex = 100) -> Frame:
        ...
    def reset_counters(self) -> None:
        ...
    def reset_device(self) -> None:
        ...
    def set_disconnect_callback(self, callback: collections.abc.Callable) -> None:
        ...
    def set_sample_rate_hz(self, sample_rate_hz: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def set_streaming(self, enable: bool) -> None:
        ...
    def start_streaming(self, callback: collections.abc.Callable) -> None:
        ...
    def stop_streaming(self) -> None:
        ...
    def sync_host_epoch(self, host_unix_ns: typing.SupportsInt | typing.SupportsIndex) -> SyncResult:
        ...
class Handedness:
    """
    Members:
    
      LEFT
    
      RIGHT
    """
    LEFT: typing.ClassVar[Handedness]  # value = <Handedness.LEFT: 0>
    RIGHT: typing.ClassVar[Handedness]  # value = <Handedness.RIGHT: 1>
    __members__: typing.ClassVar[dict[str, Handedness]]  # value = {'LEFT': <Handedness.LEFT: 0>, 'RIGHT': <Handedness.RIGHT: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Status:
    """
    Members:
    
      OK
    
      BAD_LENGTH
    
      BAD_CRC
    
      UNKNOWN_CMD
    
      BAD_PAYLOAD
    """
    BAD_CRC: typing.ClassVar[Status]  # value = <Status.BAD_CRC: 17>
    BAD_LENGTH: typing.ClassVar[Status]  # value = <Status.BAD_LENGTH: 16>
    BAD_PAYLOAD: typing.ClassVar[Status]  # value = <Status.BAD_PAYLOAD: 19>
    OK: typing.ClassVar[Status]  # value = <Status.OK: 0>
    UNKNOWN_CMD: typing.ClassVar[Status]  # value = <Status.UNKNOWN_CMD: 18>
    __members__: typing.ClassVar[dict[str, Status]]  # value = {'OK': <Status.OK: 0>, 'BAD_LENGTH': <Status.BAD_LENGTH: 16>, 'BAD_CRC': <Status.BAD_CRC: 17>, 'UNKNOWN_CMD': <Status.UNKNOWN_CMD: 18>, 'BAD_PAYLOAD': <Status.BAD_PAYLOAD: 19>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SyncResult:
    @property
    def device_ns_at_sync(self) -> int:
        ...
    @property
    def host_ns_echo(self) -> int:
        ...
BOOTLOADER_MAGIC: int = 2953293831
