"""Tactile board API.

Re-exports the pybind11 submodule ``wujihandpy._core.tactile`` so that
``import wujihandpy.tactile`` and ``from wujihandpy.tactile import Board``
work without leaking the ``_core`` implementation detail to users.

Mirrors ``wujihandcpp::tactile`` on the C++ side.

Implementation note: imports are derived dynamically from the native
submodule's ``__all__`` so the wrapper never drifts when the C++ side
adds or removes a tactile type. Static type-checkers see the matching
re-export shape via ``tactile.pyi`` (regenerated by ``update_stubs.py``
from ``_core/tactile.pyi``'s ``__all__``).
"""

from __future__ import annotations

from wujihandpy._core import tactile as _tactile_module
from wujihandpy._core.tactile import *  # noqa: F401,F403

__all__ = list(_tactile_module.__all__)
