"""Type stub for wujihandpy.tactile (generated by update_stubs.py)."""

from __future__ import annotations

from ._core.tactile import (
    BOOTLOADER_MAGIC as BOOTLOADER_MAGIC,
    DeviceInfo as DeviceInfo,
    DeviceTime as DeviceTime,
    Diagnostics as Diagnostics,
    Error as Error,
    Frame as Frame,
    FwBuild as FwBuild,
    Glove as Glove,
    Handedness as Handedness,
    Status as Status,
    SyncResult as SyncResult,
)

__all__: list[str] = [
    "BOOTLOADER_MAGIC",
    "DeviceInfo",
    "DeviceTime",
    "Diagnostics",
    "Error",
    "Frame",
    "FwBuild",
    "Glove",
    "Handedness",
    "Status",
    "SyncResult",
]
